#Ryan Schreck | CIS4930 | Assignment 8

#Define openapi version
openapi: 3.0.3
#File description
info:
  title: Movie Ticket Payment API
  description: This API allows users to make, retrieve, and delete payments related to online movie ticket purchases. It supports basic operations like creating a new payment, checking payment status, and canceling a payment if needed.
  version: 1.0.0

#API endpoint to make a payment
paths:
  /payments:
    post:
      summary: Make a payment for movie tickets
      operationId: makePayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
                - showId
                - seatNumbers
                - paymentMethod
              properties:
                userId:
                  type: string
                  description: Unique ID of the customer making the payment
                showId:
                  type: string
                  description: Identifier for the movie showtime
                seatNumbers:
                  type: array
                  items:
                    type: string
                  description: List of selected seat numbers
                paymentMethod:
                  type: object
                  required:
                    - type
                    - details
                  properties:
                    type:
                      type: string
                      description: Type of payment method
                    details:
                      type: object # card number, expiry, etc
                      description: Payment details
                totalAmount:
                  type: number
                  format: float
                  description: Total amount to be charged
      responses:
        '200':
          description: Payment successful
        '400':
          description: Invalid request # missing fields or invalid payment method etc
        '500':
          description: Server error during payment processing
  /payments/{paymentId}:
      get:
        summary: Retrieve a payment by ID
        parameters:
          - name: paymentId
            in: path
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Payment found
          '404':
            description: Payment not found

      delete:
        summary: Cancel a payment by ID
        parameters:
          - name: paymentId
            in: path
            required: true
            schema:
              type: string
        responses:
          '200':
            description: Payment successfully canceled
          '404':
            description: Payment not found
          '500':
            description: Server error during cancellation


